openapi: 3.2.0
info:
  title: Alleva Rest Pronoun API
  version: '1.0'
security:
- Bearer: []
tags:
- name: Pronoun
paths:
  /pronoun:
    post:
      tags:
      - Pronoun
      parameters:
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Pronoun'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Pronoun'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Pronoun'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Pronoun'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
      summary: Create pronoun
      x-summary-source: derived
      operationId: postPronoun
      x-operation-id-source: derived
    get:
      tags:
      - Pronoun
      parameters:
      - name: Limit
        in: query
        schema:
          type: integer
          format: int64
      - name: Cursor
        in: query
        schema:
          type: integer
          format: int32
      - name: StartDate
        in: query
        schema:
          type: string
          format: date-time
      - name: EndDate
        in: query
        schema:
          type: string
          format: date-time
      - name: fields
        in: query
        schema:
          type: array
          items:
            type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pronoun'
            application/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pronoun'
            text/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pronoun'
      summary: Get pronoun
      x-summary-source: derived
      operationId: getPronoun
      x-operation-id-source: derived
  /v{version}/pronoun:
    post:
      tags:
      - Pronoun
      parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Pronoun'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Pronoun'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Pronoun'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Pronoun'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
      summary: Create v{version} pronoun
      x-summary-source: derived
      operationId: postV{version}Pronoun
      x-operation-id-source: derived
    get:
      tags:
      - Pronoun
      parameters:
      - name: Limit
        in: query
        schema:
          type: integer
          format: int64
      - name: Cursor
        in: query
        schema:
          type: integer
          format: int32
      - name: StartDate
        in: query
        schema:
          type: string
          format: date-time
      - name: EndDate
        in: query
        schema:
          type: string
          format: date-time
      - name: fields
        in: query
        schema:
          type: array
          items:
            type: string
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pronoun'
            application/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pronoun'
            text/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pronoun'
      summary: Get v{version} pronoun
      x-summary-source: derived
      operationId: getV{version}Pronoun
      x-operation-id-source: derived
  /pronoun/{id}:
    delete:
      tags:
      - Pronoun
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
      summary: Delete pronoun by id
      x-summary-source: derived
      operationId: deletePronounById
      x-operation-id-source: derived
    patch:
      tags:
      - Pronoun
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
      summary: Update pronoun by id
      x-summary-source: derived
      operationId: patchPronounById
      x-operation-id-source: derived
    get:
      tags:
      - Pronoun
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
      summary: Get pronoun by id
      x-summary-source: derived
      operationId: getPronounById
      x-operation-id-source: derived
  /v{version}/pronoun/{id}:
    delete:
      tags:
      - Pronoun
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
      summary: Delete v{version} pronoun by id
      x-summary-source: derived
      operationId: deleteV{version}PronounById
      x-operation-id-source: derived
    patch:
      tags:
      - Pronoun
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
      summary: Update v{version} pronoun by id
      x-summary-source: derived
      operationId: patchV{version}PronounById
      x-operation-id-source: derived
    get:
      tags:
      - Pronoun
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Pronoun'
      summary: Get v{version} pronoun by id
      x-summary-source: derived
      operationId: getV{version}PronounById
      x-operation-id-source: derived
components:
  schemas:
    Pronoun:
      type: object
      properties:
        id:
          type: integer
          format: int32
        href:
          type:
          - string
          - 'null'
          readOnly: true
        name:
          type:
          - string
          - 'null'
        isActive:
          type: boolean
        inUse:
          type: boolean
      additionalProperties: false
    JToken:
      type: array
      items:
        $ref: '#/components/schemas/JToken'
  securitySchemes:
    Bearer:
      type: apiKey
      description: "JWT Authorization header using the Bearer scheme. \n\n Enter Bearer [space] and then your token in the text input below.\n\nExample: Bearer 12345abcdef"
      name: Authorization
      in: header
