openapi: 3.2.0
info:
  title: Alleva Rest User License API
  version: '1.0'
security:
- Bearer: []
tags:
- name: UserLicense
paths:
  /licenses:
    post:
      tags:
      - UserLicense
      parameters:
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/UserLicenseType'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/UserLicenseType'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/UserLicenseType'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/UserLicenseType'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
    get:
      tags:
      - UserLicense
      parameters:
      - name: Limit
        in: query
        schema:
          type: integer
          format: int64
      - name: Cursor
        in: query
        schema:
          type: integer
          format: int32
      - name: StartDate
        in: query
        schema:
          type: string
          format: date-time
      - name: EndDate
        in: query
        schema:
          type: string
          format: date-time
      - name: fields
        in: query
        schema:
          type: array
          items:
            type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserLicenseType'
            application/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserLicenseType'
            text/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserLicenseType'
  /v{version}/licenses:
    post:
      tags:
      - UserLicense
      parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/UserLicenseType'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/UserLicenseType'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/UserLicenseType'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/UserLicenseType'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
    get:
      tags:
      - UserLicense
      parameters:
      - name: Limit
        in: query
        schema:
          type: integer
          format: int64
      - name: Cursor
        in: query
        schema:
          type: integer
          format: int32
      - name: StartDate
        in: query
        schema:
          type: string
          format: date-time
      - name: EndDate
        in: query
        schema:
          type: string
          format: date-time
      - name: fields
        in: query
        schema:
          type: array
          items:
            type: string
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserLicenseType'
            application/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserLicenseType'
            text/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserLicenseType'
  /licenses/{id}:
    delete:
      tags:
      - UserLicense
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
    patch:
      tags:
      - UserLicense
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
    get:
      tags:
      - UserLicense
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
  /v{version}/licenses/{id}:
    delete:
      tags:
      - UserLicense
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
    patch:
      tags:
      - UserLicense
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
    get:
      tags:
      - UserLicense
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UserLicenseType'
components:
  schemas:
    JToken:
      type: array
      items:
        $ref: '#/components/schemas/JToken'
    UserLicenseType:
      type: object
      properties:
        id:
          type: integer
          format: int32
        href:
          type:
          - string
          - 'null'
          readOnly: true
        name:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        isActive:
          type: boolean
        canModifyOrDelete:
          type: boolean
        inUse:
          type: boolean
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: "JWT Authorization header using the Bearer scheme. \n\n Enter Bearer [space] and then\
        \ your token in the text input below.\n\nExample: Bearer 12345abcdef"
      name: Authorization
      in: header
servers:
- url: https://api.helloalleva.com
  description: Base URL reconciled from apis.yml
