openapi: 3.2.0
info:
  title: Alleva Rest Rehab API
  version: '1.0'
security:
- Bearer: []
tags:
- name: Rehab
paths:
  /company/{id}/documents:
    post:
      tags:
      - Rehab
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabDocument'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabDocument'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabDocument'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabDocument'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateResult'
            application/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateResult'
            text/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateResult'
  /v{version}/company/{id}/documents:
    post:
      tags:
      - Rehab
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabDocument'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabDocument'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabDocument'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabDocument'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateResult'
            application/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateResult'
            text/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateResult'
  /company/{id}/logo:
    post:
      tags:
      - Rehab
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabLogoData'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabLogoData'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabLogoData'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabLogoData'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/UpdateResult'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UpdateResult'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UpdateResult'
  /v{version}/company/{id}/logo:
    post:
      tags:
      - Rehab
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabLogoData'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabLogoData'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabLogoData'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/RehabLogoData'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/UpdateResult'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UpdateResult'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/UpdateResult'
  /company:
    get:
      tags:
      - Rehab
      parameters:
      - name: Limit
        in: query
        schema:
          type: integer
          format: int64
      - name: Cursor
        in: query
        schema:
          type: integer
          format: int32
      - name: StartDate
        in: query
        schema:
          type: string
          format: date-time
      - name: EndDate
        in: query
        schema:
          type: string
          format: date-time
      - name: fields
        in: query
        schema:
          type: array
          items:
            type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rehab'
            application/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rehab'
            text/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rehab'
  /v{version}/company:
    get:
      tags:
      - Rehab
      parameters:
      - name: Limit
        in: query
        schema:
          type: integer
          format: int64
      - name: Cursor
        in: query
        schema:
          type: integer
          format: int32
      - name: StartDate
        in: query
        schema:
          type: string
          format: date-time
      - name: EndDate
        in: query
        schema:
          type: string
          format: date-time
      - name: fields
        in: query
        schema:
          type: array
          items:
            type: string
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rehab'
            application/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rehab'
            text/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rehab'
  /company/{id}:
    get:
      tags:
      - Rehab
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Rehab'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Rehab'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Rehab'
  /v{version}/company/{id}:
    get:
      tags:
      - Rehab
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Rehab'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Rehab'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Rehab'
components:
  schemas:
    RehabDocument:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        facilityId:
          type: integer
          format: int32
        uploadedDocuments:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DocumentData'
      additionalProperties: false
    DocumentData:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type:
          - string
          - 'null'
        base64String:
          type:
          - string
          - 'null'
        externalId:
          $ref: '#/components/schemas/ExternalData'
      additionalProperties: false
    CreateResult:
      type: object
      properties:
        operationResult:
          $ref: '#/components/schemas/CreateOperationResult'
        id:
          type:
          - integer
          - 'null'
          format: int64
        messages:
          type:
          - array
          - 'null'
          items:
            type: string
        reason:
          type:
          - string
          - 'null'
      additionalProperties: false
    Rehab:
      type: object
      properties:
        id:
          type: integer
          format: int32
        href:
          type:
          - string
          - 'null'
          readOnly: true
        rehabName:
          type:
          - string
          - 'null'
        domainName:
          type:
          - string
          - 'null'
        organizationUuid:
          type:
          - string
          - 'null'
          format: uuid
      additionalProperties: false
    ExternalData:
      type: object
      properties:
        externalId:
          type:
          - string
          - 'null'
        externalIdType:
          type:
          - string
          - 'null'
        serviceIdentifier:
          type:
          - string
          - 'null'
        serviceId:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: false
    UpdateOperationResult:
      enum:
      - 0
      - 1
      - 2
      - 3
      type: integer
      format: int32
    RehabLogoData:
      type: object
      properties:
        fileName:
          type:
          - string
          - 'null'
        base64String:
          type:
          - string
          - 'null'
      additionalProperties: false
    UpdateResult:
      type: object
      properties:
        operationResult:
          $ref: '#/components/schemas/UpdateOperationResult'
        success:
          type: boolean
        id:
          type: integer
          format: int64
        messages:
          type:
          - array
          - 'null'
          items:
            type: string
        reason:
          type:
          - string
          - 'null'
      additionalProperties: false
    CreateOperationResult:
      enum:
      - 0
      - 1
      - 2
      - 3
      type: integer
      format: int32
  securitySchemes:
    Bearer:
      type: apiKey
      description: "JWT Authorization header using the Bearer scheme. \n\n Enter Bearer [space] and then\
        \ your token in the text input below.\n\nExample: Bearer 12345abcdef"
      name: Authorization
      in: header
servers:
- url: https://api.helloalleva.com
  description: Base URL reconciled from apis.yml
