openapi: 3.2.0
info:
  title: Alleva Rest Data Value API
  version: '1.0'
security:
- Bearer: []
tags:
- name: DataValue
paths:
  /data-values/search:
    post:
      tags:
      - DataValue
      parameters:
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValuesSearch'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValuesSearch'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValuesSearch'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValuesSearch'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataValueWithKindResponse'
            application/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataValueWithKindResponse'
            text/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataValueWithKindResponse'
  /v{version}/data-values/search:
    post:
      tags:
      - DataValue
      parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValuesSearch'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValuesSearch'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValuesSearch'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValuesSearch'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataValueWithKindResponse'
            application/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataValueWithKindResponse'
            text/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataValueWithKindResponse'
  /data-values/{dataFacetId}:
    put:
      tags:
      - DataValue
      parameters:
      - name: dataFacetId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValueWithKind'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValueWithKind'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValueWithKind'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValueWithKind'
      responses:
        '200':
          description: Success
  /v{version}/data-values/{dataFacetId}:
    put:
      tags:
      - DataValue
      parameters:
      - name: dataFacetId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValueWithKind'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValueWithKind'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValueWithKind'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/DataValueWithKind'
      responses:
        '200':
          description: Success
components:
  schemas:
    DataValuesSearch:
      type: object
      properties:
        datafacetIds:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int32
        leadId:
          type: integer
          format: int32
        advancedFormInstanceId:
          type: integer
          format: int64
        advancedFormId:
          type: integer
          format: int32
      additionalProperties: false
    DataValueWithKind:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        advancedFormInstanceId:
          type: integer
          format: int64
        booleanValue:
          type:
          - boolean
          - 'null'
        createdBy:
          type:
          - integer
          - 'null'
          format: int32
        createdByUserType:
          $ref: '#/components/schemas/UserType'
        createdDate:
          type:
          - string
          - 'null'
          format: date-time
        dataFacetId:
          type: integer
          format: int32
        dateTimeValue:
          type:
          - string
          - 'null'
          format: date-time
        decimalValue:
          type:
          - number
          - 'null'
          format: double
        integerValue:
          type:
          - integer
          - 'null'
          format: int32
        imageValue:
          type:
          - string
          - 'null'
          format: byte
        jsonValue:
          type:
          - string
          - 'null'
        fileValue:
          type:
          - string
          - 'null'
        leadId:
          type: integer
          format: int32
        modifiedBy:
          type:
          - integer
          - 'null'
          format: int32
        modifiedByUserType:
          $ref: '#/components/schemas/UserType'
        modifiedDate:
          type:
          - string
          - 'null'
          format: date-time
        originalFormId:
          type: integer
          format: int32
        signatureValue:
          type:
          - string
          - 'null'
          format: byte
        stringValue:
          type:
          - string
          - 'null'
        dataKind:
          $ref: '#/components/schemas/DataKind'
      additionalProperties: false
    DataKind:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      type: integer
      format: int32
    UserType:
      enum:
      - 0
      - 1
      - 2
      type: integer
      format: int32
    DataValueWithKindResponse:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        advancedFormInstanceId:
          type: integer
          format: int64
        booleanValue:
          type:
          - boolean
          - 'null'
        dataFacetId:
          type: integer
          format: int32
        dateTimeValue:
          type:
          - string
          - 'null'
          format: date-time
        decimalValue:
          type:
          - number
          - 'null'
          format: double
        fileValue:
          type:
          - string
          - 'null'
        integerValue:
          type:
          - integer
          - 'null'
          format: int32
        imageValue:
          type:
          - string
          - 'null'
          format: byte
        jsonValue:
          type:
          - string
          - 'null'
        leadId:
          type: integer
          format: int32
        signatureValue:
          type:
          - string
          - 'null'
        stringValue:
          type:
          - string
          - 'null'
        createdDate:
          type:
          - string
          - 'null'
          format: date-time
        dataKind:
          $ref: '#/components/schemas/DataKind'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: "JWT Authorization header using the Bearer scheme. \n\n Enter Bearer [space] and then\
        \ your token in the text input below.\n\nExample: Bearer 12345abcdef"
      name: Authorization
      in: header
servers:
- url: https://api.helloalleva.com
  description: Base URL reconciled from apis.yml
