openapi: 3.2.0
info:
  title: Alleva Rest Room API
  version: '1.0'
security:
- Bearer: []
tags:
- name: Room
paths:
  /rooms:
    post:
      tags:
      - Room
      parameters:
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Room'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Room'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Room'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Room'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
      summary: Create rooms
      x-summary-source: derived
      operationId: postRooms
      x-operation-id-source: derived
    get:
      tags:
      - Room
      parameters:
      - name: Limit
        in: query
        schema:
          type: integer
          format: int64
      - name: Cursor
        in: query
        schema:
          type: integer
          format: int32
      - name: StartDate
        in: query
        schema:
          type: string
          format: date-time
      - name: EndDate
        in: query
        schema:
          type: string
          format: date-time
      - name: fields
        in: query
        schema:
          type: array
          items:
            type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
            application/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
            text/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
      summary: Get rooms
      x-summary-source: derived
      operationId: getRooms
      x-operation-id-source: derived
  /v{version}/rooms:
    post:
      tags:
      - Room
      parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Room'
          application/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Room'
          text/json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Room'
          application/*+json; ver=1.0:
            schema:
              $ref: '#/components/schemas/Room'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
      summary: Create v{version} rooms
      x-summary-source: derived
      operationId: postV{version}Rooms
      x-operation-id-source: derived
    get:
      tags:
      - Room
      parameters:
      - name: Limit
        in: query
        schema:
          type: integer
          format: int64
      - name: Cursor
        in: query
        schema:
          type: integer
          format: int32
      - name: StartDate
        in: query
        schema:
          type: string
          format: date-time
      - name: EndDate
        in: query
        schema:
          type: string
          format: date-time
      - name: fields
        in: query
        schema:
          type: array
          items:
            type: string
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
            application/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
            text/json; ver=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
      summary: Get v{version} rooms
      x-summary-source: derived
      operationId: getV{version}Rooms
      x-operation-id-source: derived
  /rooms/{id}:
    delete:
      tags:
      - Room
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
      summary: Delete rooms by id
      x-summary-source: derived
      operationId: deleteRoomsById
      x-operation-id-source: derived
    patch:
      tags:
      - Room
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
      summary: Update rooms by id
      x-summary-source: derived
      operationId: patchRoomsById
      x-operation-id-source: derived
    get:
      tags:
      - Room
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
      summary: Get rooms by id
      x-summary-source: derived
      operationId: getRoomsById
      x-operation-id-source: derived
  /v{version}/rooms/{id}:
    delete:
      tags:
      - Room
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
      summary: Delete v{version} rooms by id
      x-summary-source: derived
      operationId: deleteV{version}RoomsById
      x-operation-id-source: derived
    patch:
      tags:
      - Room
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json-patch+json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json; ver=1.0:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
      summary: Update v{version} rooms by id
      x-summary-source: derived
      operationId: patchV{version}RoomsById
      x-operation-id-source: derived
    get:
      tags:
      - Room
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: version
        in: path
        required: true
        schema:
          type: string
      - name: api-version
        in: query
        schema:
          type: string
      - name: X-Version
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            application/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
            text/json; ver=1.0:
              schema:
                $ref: '#/components/schemas/Room'
      summary: Get v{version} rooms by id
      x-summary-source: derived
      operationId: getV{version}RoomsById
      x-operation-id-source: derived
components:
  schemas:
    JToken:
      type: array
      items:
        $ref: '#/components/schemas/JToken'
    Room:
      type: object
      properties:
        id:
          type: integer
          format: int32
        href:
          type:
          - string
          - 'null'
          readOnly: true
        facilityId:
          type: integer
          format: int32
        roomName:
          type:
          - string
          - 'null'
        isActive:
          type: boolean
        totalBeds:
          type: integer
          format: int32
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: "JWT Authorization header using the Bearer scheme. \n\n Enter Bearer [space] and then your token in the text input below.\n\nExample: Bearer 12345abcdef"
      name: Authorization
      in: header
